import type { Location, Translations, Language } from './types';

export const initialLocations: Location[] = [
  { id: '1', name: 'Barcelona, Spain', lat: 41.3851, lng: 2.1734, date: '2023-05-20', country: 'Spain', continent: 'Europe' },
  { id: '2', name: 'New York, USA', lat: 40.7128, lng: -74.0060, date: '2022-11-15', country: 'USA', continent: 'North America' },
  { id: '3', name: 'Tokyo, Japan', lat: 35.6895, lng: 139.6917, date: '2024-03-10', country: 'Japan', continent: 'Asia' },
  { id: '4', name: 'Sydney, Australia', lat: -33.8688, lng: 151.2093, date: '2023-01-25', country: 'Australia', continent: 'Australia' },
  { id: '5', name: 'Cairo, Egypt', lat: 30.0444, lng: 31.2357, date: '2023-09-02', country: 'Egypt', continent: 'Africa' },
  { id: '6', name: 'Rio de Janeiro, Brazil', lat: -22.9068, lng: -43.1729, date: '2024-02-18', country: 'Brazil', continent: 'South America' },
  { id: '7', name: 'Paris, France', lat: 48.8566, lng: 2.3522, date: '2023-06-12', country: 'France', continent: 'Europe' },
  { id: '8', name: 'London, UK', lat: 51.5074, lng: -0.1278, date: '2023-07-01', country: 'United Kingdom', continent: 'Europe' },
];

export const translations: Translations = {
  ca: {
    appName: 'GeoRecorregut',
    search: 'Cerca',
    stats: 'Estadístiques',
    data: 'Dades',
    searchPlaceholder: 'Cerca una ubicació...',
    noResults: 'No s\'han trobat resultats.',
    locationsVisited: 'Ubicacions Visitades',
    continentsVisited: 'Continents Visitats',
    countriesVisited: 'Països Visitats',
    recordLocation: 'Enregistrar Ubicació Actual',
    importData: 'Importar Dades',
    exportData: 'Exportar Dades',
    importCSV: 'Importar CSV',
    importGPX: 'Importar GPX',
    importGoogle: 'Importar de Google',
    exportAsJSON: 'Exportar com a JSON',
    language: 'Idioma',
    catalan: 'Català',
    spanish: 'Espanyol',
    english: 'Anglès',
    profile: 'Perfil',
    settings: 'Configuració',
    logout: 'Tancar sessió',
    loginTitle: 'Benvingut de nou',
    loginSubtitle: 'Inicia sessió al teu compte',
    email: 'Correu electrònic',
    password: 'Contrasenya',
    login: 'Iniciar sessió',
    noAccount: 'No tens un compte?',
    signup: 'Registra\'t',
    signupTitle: 'Crea un Compte',
    signupSubtitle: 'Comença el teu viatge amb nosaltres',
    haveAccount: 'Ja tens un compte?',
    locationRecorded: 'Ubicació actual enregistrada!',
    errorRecording: 'Error en enregistrar la ubicació.',
    dataExported: 'Dades exportades correctament!',
  },
  es: {
    appName: 'GeoRecorrido',
    search: 'Buscar',
    stats: 'Estadísticas',
    data: 'Datos',
    searchPlaceholder: 'Busca una ubicación...',
    noResults: 'No se encontraron resultados.',
    locationsVisited: 'Ubicaciones Visitadas',
    continentsVisited: 'Continentes Visitados',
    countriesVisited: 'Países Visitados',
    recordLocation: 'Registrar Ubicación Actual',
    importData: 'Importar Datos',
    exportData: 'Exportar Datos',
    importCSV: 'Importar CSV',
    importGPX: 'Importar GPX',
    importGoogle: 'Importar de Google',
    exportAsJSON: 'Exportar como JSON',
    language: 'Idioma',
    catalan: 'Catalán',
    spanish: 'Español',
    english: 'Inglés',
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar sesión',
    loginTitle: 'Bienvenido de nuevo',
    loginSubtitle: 'Inicia sesión en tu cuenta',
    email: 'Correo electrónico',
    password: 'Contraseña',
    login: 'Iniciar sesión',
    noAccount: '¿No tienes una cuenta?',
    signup: 'Regístrate',
    signupTitle: 'Crea una Cuenta',
    signupSubtitle: 'Empieza tu viaje con nosotros',
    haveAccount: '¿Ya tienes una cuenta?',
    locationRecorded: '¡Ubicación actual registrada!',
    errorRecording: 'Error al registrar la ubicación.',
    dataExported: '¡Datos exportados correctamente!',
  },
  en: {
    appName: 'GeoJourney',
    search: 'Search',
    stats: 'Statistics',
    data: 'Data',
    searchPlaceholder: 'Search for a location...',
    noResults: 'No results found.',
    locationsVisited: 'Locations Visited',
    continentsVisited: 'Continents Visited',
    countriesVisited: 'Countries Visited',
    recordLocation: 'Record Current Location',
    importData: 'Import Data',
    exportData: 'Export Data',
    importCSV: 'Import CSV',
    importGPX: 'Import GPX',
    importGoogle: 'Import from Google',
    exportAsJSON: 'Export as JSON',
    language: 'Language',
    catalan: 'Catalan',
    spanish: 'Spanish',
    english: 'English',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to your account',
    email: 'Email',
    password: 'Password',
    login: 'Log in',
    noAccount: 'Don\'t have an account?',
    signup: 'Sign up',
    signupTitle: 'Create an Account',
    signupSubtitle: 'Start your journey with us',
    haveAccount: 'Already have an account?',
    locationRecorded: 'Current location recorded!',
    errorRecording: 'Error recording location.',
    dataExported: 'Data exported successfully!',
  },
};

export const getTranslation = (lang: Language) => (key: string) => translations[lang][key] || key;
