import type { Location, Translations, Language } from './types';

export const initialLocations: Location[] = [];

export const translations: Translations = {
  ca: {
    appName: 'GeoRecorregut',
    search: 'Cerca',
    stats: 'Estadístiques',
    data: 'Dades',
    searchPlaceholder: 'Cerca llocs nous...',
    noResults: 'No s\'han trobat resultats.',
    locationsVisited: 'Ubicacions Visitades',
    continentsVisited: 'Continents Visitats',
    csvFormatInfo: 'Format del Fitxer CSV (valors separats per punt i coma): Hi ha dues columnes obligatòries, una amb el País (Country) i una columna amb la Ciutat (City). Columna opciona (Favorite) per identificar les favorites. Altres columnes seran ignorades',
    countriesVisited: 'Països Visitats',
    importData: 'Importar Dades',
    exportData: 'Exportar Dades',
    importCSV: 'Importar CSV',
    importGPX: 'Importar GPX',
    importGoogle: 'Importar de Google',
    exportAsJSON: 'Exportar com a JSON',
    language: 'Idioma',
    catalan: 'Català',
    spanish: 'Espanyol',
    english: 'Anglès',
    profile: 'Perfil',
    settings: 'Configuració',
    logout: 'Tancar sessió',
    loginTitle: 'Benvingut de nou',
    loginSubtitle: 'Inicia sessió al teu compte',
    email: 'Correu electrònic',
    password: 'Contrasenya',
    login: 'Iniciar sessió',
    noAccount: 'No tens un compte?',
    signup: 'Registra\'t',
    signupTitle: 'Crea un Compte',
    signupSubtitle: 'Comença el teu viatge amb nosaltres',
    haveAccount: 'Ja tens un compte?',
    locationRecorded: 'Ubicació actual enregistrada!',
    errorRecording: 'Error en enregistrar la ubicació.',
    dataExported: 'Dades exportades correctament!',
    searching: 'Cercant...',
    searchResults: 'Resultats de la Cerca',
    myLocations: 'Les Meves Ubicacions',
    noLocations: 'Encara no has desat cap ubicació.',
    locationAdded: 'Ubicació afegida',
    hasBeenAdded: 's\'ha afegit a les teves ubicacions.'
  },
  es: {
    appName: 'GeoRecorrido',
    search: 'Buscar',
    stats: 'Estadísticas',
    data: 'Datos',
    searchPlaceholder: 'Busca nuevos lugares...',
    noResults: 'No se encontraron resultados.',
    locationsVisited: 'Ubicaciones Visitadas',
    continentsVisited: 'Continentes Visitados',
    csvFormatInfo: 'Formato del Archivo CSV (valores separados por punto y comas): Hay dos columnas obligatorias, una con el País (Country) y una columna con la Ciudad (City). Una columna opcional (Favorite) para marcar favoritos. Otras columnas serán ignoradas',
    countriesVisited: 'Países Visitados',
    importData: 'Importar Datos',
    exportData: 'Exportar Datos',
    importCSV: 'Importar CSV',
    importGPX: 'Importar GPX',
    importGoogle: 'Importar de Google',
    exportAsJSON: 'Exportar como JSON',
    language: 'Idioma',
    catalan: 'Catalán',
    spanish: 'Español',
    english: 'Inglés',
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar sesión',
    loginTitle: 'Bienvenido de nuevo',
    loginSubtitle: 'Inicia sesión en tu cuenta',
    email: 'Correo electrónico',
    password: 'Contraseña',
    login: 'Iniciar sesión',
    noAccount: '¿No tienes una cuenta?',
    signup: 'Regístrate',
    signupTitle: 'Crea una Cuenta',
    signupSubtitle: 'Empieza tu viaje con nosotros',
    haveAccount: '¿Ya tienes una cuenta?',
    locationRecorded: '¡Ubicación actual registrada!',
    errorRecording: 'Error al registrar la ubicación.',
    dataExported: '¡Datos exportados correctamente!',
    searching: 'Buscando...',
    searchResults: 'Resultados de la Búsqueda',
    myLocations: 'Mis Ubicaciones',
    noLocations: 'Aún no has guardado ninguna ubicación.',
    locationAdded: 'Ubicación añadida',
    hasBeenAdded: 'se ha añadido a tus ubicaciones.'
  },
  en: {
    appName: 'GeoJourney',
    search: 'Search',
    stats: 'Statistics',
    data: 'Data',
    searchPlaceholder: 'Search for new places...',
    noResults: 'No results found.',
    locationsVisited: 'Locations Visited',
    continentsVisited: 'Continents Visited',
    csvFormatInfo: 'Format of the CSV File (point-comma ; separated value): There are two mandatory columns, one with the Country (Country) and a column with the City (City). Another optional column (Favorite) to import as favorite location. Other columns will be ignored',
    countriesVisited: 'Countries Visited',
    importData: 'Import Data',
    exportData: 'Export Data',
    importCSV: 'Import CSV',
    importGPX: 'Import GPX',
    importGoogle: 'Import from Google',
    exportAsJSON: 'Export as JSON',
    language: 'Language',
    catalan: 'Catalan',
    spanish: 'Spanish',
    english: 'English',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to your account',
    email: 'Email',
    password: 'Password',
    login: 'Log in',
    noAccount: 'Don\'t have an account?',
    signup: 'Sign up',
    signupTitle: 'Create an Account',
    subtitle: 'Start your journey with us',
    haveAccount: 'Already have an account?',
    locationRecorded: 'Current location recorded!',
    errorRecording: 'Error recording location.',
    dataExported: 'Data exported successfully!',
    searching: 'Searching...',
    searchResults: 'Search Results',
    myLocations: 'My Locations',
    noLocations: 'You haven\'t saved any locations yet.',
    locationAdded: 'Location Added',
  },
};

export const getTranslation = (lang: Language) => (key: string) => translations[lang][key] || key;

export const Continents = {
  "Europe": ["AL", "AD", "AM", "AT", "BY", "BE", "BA", "BG", "CH", "CY", "CZ", "DE", "DK", "EE", "ES", "FO", "FI", "FR", "GB", "GE", "GI", "GR", "HU", "HR", "IE", "IS", "IT", "LT", "LU", "LV", "MC", "MK", "MT", "NO", "NL", "PL", "PT", "RO", "RU", "SE", "SI", "SK", "SM", "UA", "VA"],
  "Asia": ["AE", "AF", "AM", "AZ", "BD", "BH", "BN", "BT", "CN", "CY", "GE", "ID", "IL", "IN", "IQ", "IR", "JO", "JP", "KG", "KH", "KP", "KR", "KW", "KZ", "LA", "LB", "LK", "MM", "MN", "MO", "MV", "MY", "NP", "OM", "PH", "PK", "PS", "QA", "SA", "SG", "SY", "TH", "TJ", "TL", "TM", "TR", "TW", "UZ", "VN", "YE"],
  "Africa": ["AO", "BF", "BI", "BJ", "BW", "CD", "CF", "CG", "CI", "CM", "CV", "DJ", "DZ", "EG", "EH", "ER", "ET", "GA", "GH", "GM", "GN", "GQ", "GW", "KE", "KM", "LR", "LS", "LY", "MA", "MG", "ML", "MR", "MU", "MW", "MZ", "NA", "NE", "NG", "RE", "RW", "SC", "SD", "SH", "SL", "SN", "SO", "ST", "SZ", "TD", "TG", "TN", "TZ", "UG", "YT", "ZA", "ZM", "ZW"],
  "North America": ["AG", "AI", "AW", "BB", "BL", "BM", "BS", "BZ", "CA", "CR", "CU", "DM", "DO", "GD", "GL", "GP", "GT", "HN", "HT", "JM", "KN", "KY", "LC", "MF", "MQ", "MS", "MX", "NI", "PA", "PM", "PR", "SV", "TC", "TT", "US", "VC", "VG", "VI"],
  "South America": ["AR", "BO", "BR", "CL", "CO", "EC", "FK", "GF", "GY", "PE", "PY", "SR", "UY", "VE"],
  "Oceania": ["AS", "AU", "CK", "FJ", "FM", "GU", "KI", "MH", "MP", "NC", "NF", "NR", "NU", "NZ", "PF", "PG", "PN", "PW", "SB", "TK", "TO", "TV", "UM", "VU", "WF", "WS"],
  "Antarctica": ["AQ", "GS", "TF"]
}
